### ISSUE TITLE
Deprecation of lavaan::duplicationMatrix

### ISSUE THREAD

**Issue by aaroncharlton** [daob/lavaan.survey#1]
Hi.
I am having difficulty using the lavaan.survey function. It seems that it is using a deprecated lavaan function, so I'm getting an error when I run it. 

Warning message:
'lavaan::duplicationMatrix' is deprecated.
Use 'lav_matrix_duplication' instead.
See help("Deprecated") and help("lavaan-deprecated"). 

More information is in the Lavaan Google Group: https://groups.google.com/forum/#!topic/lavaan/yEUcJEWAPq4

**Comment by daob** [comment]
Thanks for reporting, this issue has been solved in the last release.
